name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: '8.0.x'
    
    - name: Restore
      run: dotnet restore ./PHPServiceGenerator.sln
    
    - name: Build
      run: dotnet build ./PHPServiceGenerator.sln --configuration Release
    
    - name: Publish
      run: dotnet publish ./KoGenerator.csproj --configuration Release --no-build --output './publish'
      
    - name: Deployment
      uses: azure/webapps-deploy@v2
      with:
        app-name: php-service-generator
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: './publish'
